name: Persistent Environment Check
on:
  pull_request:

env:
  SERVICE: "tyk"
  CONTAINER_NAME: "tyk"
  CLUSTER: "kikitest"
  REGISTRY: "754489498669.dkr.ecr.eu-central-1.amazonaws.com"
  IMAGE: "tyk:v4.0.0"
  ENV_EXIST: 'true'

jobs:
  Create-workflow:
    uses: ./.github/workflows/create-persistent-env.yml
    with:
      service: ${{ SERVICE }}
      containerName: ${{ CONTAINER_NAME }}
      cluster: ${{ CLUSTER }}
      exist: ${{ ENV_EXIST }}
    

  # Update:
  #   # needs:
  #   #   - Check
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       if: env.ENV_EXIST == 'true'
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 1

  #     - name: Configure AWS credentials for use
  #       if: env.ENV_EXIST == 'true'
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.GROMIT_AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.GROMIT_AWS_SECRET_ACCESS_KEY }}
  #         aws-region: "eu-central-1"

  #     - name: Download task definition
  #       if: env.ENV_EXIST == 'true'
  #       working-directory: ./ci/terraform/environment
  #       run: |
  #         aws ecs describe-task-definition --task-definition ${CONTAINER_NAME}-${CLUSTER}-template --query taskDefinition > task-definition.json

  #     - name: Describe task definition
  #       if: env.ENV_EXIST == 'true'
  #       working-directory: ./ci/terraform/environment
  #       run: cat task-definition.json

  #     - name: Fill in the new image ID in the Amazon ECS task definition
  #       if: env.ENV_EXIST == 'true'
  #       id: task-def
  #       uses: aws-actions/amazon-ecs-render-task-definition@v1.1.1
  #       with:
  #         task-definition: ./ci/terraform/environment/task-definition.json
  #         container-name: ${{ env.CONTAINER_NAME }}
  #         image: ${{ env.REGISTRY }}/${{ env.IMAGE }}

  #     - name: Deploy to Amazon ECS
  #       if: env.ENV_EXIST == 'true'
  #       uses: aws-actions/amazon-ecs-deploy-task-definition@v1.4.9
  #       with:
  #         task-definition: ./ci/terraform/environment/task-definition.json
  #         service: ${{ env.SERVICE }}
  #         cluster: ${{ env.CLUSTER }}
  #         wait-for-service-stability: true