name: build
on:
  push:
    branches:
      - master
o  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      
      -  uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/tykio/tyk-gateway:v3.2
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
